# Generated by Django 4.0.1 on 2022-02-16 16:53

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_location_y', models.IntegerField()),
                ('icon_width', models.IntegerField()),
                ('icon_height', models.IntegerField()),
                ('icon_angle', models.IntegerField()),
                ('book_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('book_title', models.CharField(max_length=100)),
                ('font', models.CharField(max_length=100)),
            ],
        ),
    ]
