# Generated by Django 3.1.13 on 2022-01-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
