# Generated by Django 4.0.1 on 2022-02-16 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{4}-\\d{4}$')], verbose_name='전화번호'),
        ),
    ]
