# Generated by Django 3.1.13 on 2022-01-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
