# Generated by Django 4.0 on 2022-01-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0003_alter_user_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.CharField(max_length=30),
        ),
    ]
